title: Introduction To Mathematical Optimization
logo: /assets/img/logo.gif
description: Friday, August 5th (1:00 PM - 4:00 PM) & Monday, August 8th (1:00 PM - 4:00 PM)
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
